/* Generated from ../../design-tokens/tokens.json. Do not edit directly. */
export const designTokens = {
  meta: {
    version: 1,
    defaultTheme: "system",
    themeStorageKey: "mhw-theme",
  },
  primitives: {
    color: {
      neutral0: "#FFFFFF",
      neutral100: "#F4F9F0",
      neutral300: "#DCE2D8",
      neutral500: "#A4B2BC",
      neutral700: "#5E6875",
      neutral900: "#343625",
      neutral1000: "#1F2B1D",
      green200: "#BFE0A5",
      green700: "#43553A",
      green800: "#075E3B",
      greenSurface: "#D9F5E8",
      coral500: "#EA7C69",
      orange400: "#F09D65",
      blue600: "#275DAD",
      blueSurface: "#DCEBFF",
      yellow800: "#6B5700",
      yellowSurface: "#FFF4C2",
      red700: "#A30707",
      red800: "#842029",
      redSurface: "#F8D7DA",
    },
    fontFamily: {
      heading: ["Barlow", "Arial", "sans-serif"],
      body: ["Open Sans", "Arial", "sans-serif"],
      mono: ["ui-monospace", "Menlo", "monospace"],
    },
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 20,
      xl: 24,
      "2xl": 32,
      "3xl": 48,
    },
    fontWeight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      tight: 1.2,
      heading: 1.4,
      body: 1.5,
    },
    space: {
      "0": 0,
      "1": 4,
      "2": 8,
      "3": 12,
      "4": 16,
      "5": 20,
      "6": 24,
      "8": 32,
      "10": 40,
      "12": 48,
      "16": 64,
    },
    size: {
      controlSm: 40,
      controlMd: 48,
      contentSm: 440,
      contentMd: 720,
    },
    borderWidth: {
      thin: 1,
      strong: 2,
    },
    radius: {
      sm: 6,
      md: 10,
      lg: 16,
      pill: 999,
    },
    shadow: {
      sm: {
        x: 0,
        y: 2,
        blur: 6,
        spread: 0,
        color: "rgba(31, 43, 29, 0.16)",
      },
      md: {
        x: 0,
        y: 8,
        blur: 24,
        spread: 0,
        color: "rgba(31, 43, 29, 0.2)",
      },
    },
    duration: {
      instant: 0,
      fast: 120,
      normal: 200,
    },
    easing: {
      standard: "cubic-bezier(0.2, 0, 0, 1)",
    },
    zIndex: {
      base: 0,
      navigation: 100,
      overlay: 1000,
      toast: 5000,
    },
  },
  semantic: {
    typography: {
      headingFamily: ["Barlow", "Arial", "sans-serif"],
      bodyFamily: ["Open Sans", "Arial", "sans-serif"],
      bodySize: 16,
      bodyLineHeight: 1.5,
      headingWeight: 600,
      actionWeight: 600,
    },
    space: {
      controlInline: 16,
      controlBlock: 12,
      card: 24,
      section: 40,
    },
    size: {
      controlMinHeight: 48,
    },
    borderWidth: {
      default: 1,
      focus: 2,
    },
    radius: {
      control: 6,
      card: 10,
    },
    shadow: {
      card: {
        x: 0,
        y: 2,
        blur: 6,
        spread: 0,
        color: "rgba(31, 43, 29, 0.16)",
      },
      overlay: {
        x: 0,
        y: 8,
        blur: 24,
        spread: 0,
        color: "rgba(31, 43, 29, 0.2)",
      },
    },
    motion: {
      durationFast: 120,
      durationNormal: 200,
      easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    },
    zIndex: {
      navigation: 100,
      overlay: 1000,
      toast: 5000,
    },
  },
  themes: {
    light: {
      color: {
        backgroundCanvas: "#F4F9F0",
        backgroundSurface: "#FFFFFF",
        backgroundElevated: "#FFFFFF",
        textPrimary: "#1F2B1D",
        textSecondary: "#43553A",
        textMuted: "#5E6875",
        textInverse: "#F4F9F0",
        borderSubtle: "#DCE2D8",
        borderStrong: "#43553A",
        accent: "#EA7C69",
        actionPrimaryBackground: "#43553A",
        actionPrimaryText: "#F4F9F0",
        actionSecondaryBackground: "#BFE0A5",
        actionSecondaryText: "#343625",
        actionDisabledBackground: "#DCE2D8",
        actionDisabledText: "#5E6875",
        actionDangerBackground: "#A30707",
        actionDangerText: "#FFFFFF",
        focusRing: "#275DAD",
        statusSuccessText: "#075E3B",
        statusSuccessSurface: "#D9F5E8",
        statusInfoText: "#275DAD",
        statusInfoSurface: "#DCEBFF",
        statusWarningText: "#6B5700",
        statusWarningSurface: "#FFF4C2",
        statusErrorText: "#842029",
        statusErrorSurface: "#F8D7DA",
        navigationBackground: "#43553A",
        navigationText: "#F4F9F0",
        navigationActive: "#EA7C69",
        fieldBackground: "#FFFFFF",
        fieldText: "#1F2B1D",
        fieldBorder: "#A4B2BC",
        dataExpense: "#A30707",
        dataIncome: "#075E3B",
        dataForecast: "#275DAD",
      },
    },
    dark: {
      color: {
        backgroundCanvas: "#43553A",
        backgroundSurface: "#343625",
        backgroundElevated: "#343625",
        textPrimary: "#F4F9F0",
        textSecondary: "#BFE0A5",
        textMuted: "#A4B2BC",
        textInverse: "#1F2B1D",
        borderSubtle: "#BFE0A5",
        borderStrong: "#EA7C69",
        accent: "#EA7C69",
        actionPrimaryBackground: "#EA7C69",
        actionPrimaryText: "#1F2B1D",
        actionSecondaryBackground: "#BFE0A5",
        actionSecondaryText: "#343625",
        actionDisabledBackground: "#5E6875",
        actionDisabledText: "#DCE2D8",
        actionDangerBackground: "#F8D7DA",
        actionDangerText: "#842029",
        focusRing: "#F09D65",
        statusSuccessText: "#075E3B",
        statusSuccessSurface: "#D9F5E8",
        statusInfoText: "#275DAD",
        statusInfoSurface: "#DCEBFF",
        statusWarningText: "#6B5700",
        statusWarningSurface: "#FFF4C2",
        statusErrorText: "#842029",
        statusErrorSurface: "#F8D7DA",
        navigationBackground: "#343625",
        navigationText: "#F4F9F0",
        navigationActive: "#EA7C69",
        fieldBackground: "#343625",
        fieldText: "#F4F9F0",
        fieldBorder: "#BFE0A5",
        dataExpense: "#EA7C69",
        dataIncome: "#BFE0A5",
        dataForecast: "#F09D65",
      },
    },
  },
} as const;

export const { meta, primitives, semantic, themes } = designTokens;

export type ThemeName = keyof typeof themes;
export type ThemeTokens = (typeof themes)[ThemeName];
